import { Head, Link } from '../../navigation';
import { ArrowRight, ClipboardCheck, Layers } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AppLayout } from '../../layouts/AppLayout';
import { EmptyState, ErrorState, LoadingState } from '../../components/States';
import { useApi } from '../../hooks/useApi';
import { apiGet } from '../../services/api';
import type { LearningModule, Unit, Evaluation } from '../../types';
export default function Level({level}:{level:{id:number;name:string;code:string}}){const modules=useApi<LearningModule[]>(`/levels/${level.id}/modules`);const evaluations=useApi<Evaluation[]>(`/levels/${level.id}/evaluations`);const [units,setUnits]=useState<Record<number,Unit[]>>({});useEffect(()=>{let active=true;if(modules.data)Promise.all(modules.data.map(async m=>[m.id,await apiGet<Unit[]>(`/modules/${m.id}/units`)] as const)).then(rows=>{if(active)setUnits(Object.fromEntries(rows))}).catch(()=>{});return()=>{active=false}},[modules.data]);return <AppLayout title={`Nivel ${level.name}`} subtitle="Selecciona una unidad para explorar sus lecciones."><Head title={`Nivel ${level.name}`}/><Link className="mb-7 inline-block text-sm font-bold text-forest" href="/aprender">← Volver a mis niveles</Link>{modules.loading?<LoadingState/>:modules.error?<ErrorState message={modules.error}/>:!modules.data?.length?<EmptyState title="Aún no hay módulos" description="El contenido de este nivel estará disponible pronto."/>:<div className="space-y-6">{modules.data.map((module,index)=><section className="glass-panel p-6" key={module.id}><div className="mb-5 flex items-start gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100 text-forest"><Layers size={21}/></span><div><span className="eyebrow">MÓDULO {index+1}</span><h2 className="font-serif text-2xl">{module.title}</h2><p className="text-muted">{module.description}</p></div></div><div className="grid gap-3 md:grid-cols-2">{units[module.id]?.map((unit,i)=><Link key={unit.id} href={`/aprender/unidad/${unit.id}`} className="card-hover flex items-center justify-between rounded-2xl border border-emerald-100 bg-white/70 p-5"><div><small className="text-muted">Unidad {i+1}</small><h3 className="font-bold text-ink">{unit.title}</h3><p className="text-sm text-muted">{unit.description}</p></div><ArrowRight className="shrink-0 text-forest" size={20}/></Link>)}{units[module.id]?.length===0&&<p className="text-sm text-muted">Sin unidades publicadas.</p>}</div></section>)}</div>}{Boolean(evaluations.data?.length)&&<section className="mt-9"><h2 className="mb-4 font-serif text-3xl">Evaluaciones</h2><div className="grid gap-4 md:grid-cols-2">{evaluations.data?.map(item=><Link key={item.id} href={`/aprender/evaluacion/${item.id}`} className="glass-panel card-hover flex items-center gap-4 p-6"><ClipboardCheck className="text-forest"/><span className="flex-1"><strong className="block">{item.title}</strong><small className="text-muted">Nota mínima: {item.passing_score}%</small></span><ArrowRight size={18}/></Link>)}</div></section>}</AppLayout>}
