[PHP]
extension_dir="C:/Users/said_/AppData/Local/Microsoft/WinGet/Packages/PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe/ext"
extension=openssl
extension=mbstring
extension=pdo_pgsql
extension=pgsql
extension=curl
extension=fileinfo
extension=gd
date.timezone=America/Guayaquil
extension=pdo_sqlite
