<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE unidades (
    id_unidad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_modulo bigint NOT NULL REFERENCES modulos (id_modulo) ON DELETE RESTRICT,
    titulo_unidad varchar(180) NOT NULL,
    objetivo_unidad text NOT NULL,
    orden_unidad integer NOT NULL CHECK (orden_unidad > 0),
    UNIQUE (id_modulo, orden_unidad)
);
CREATE INDEX ix_unidades_id_modulo ON unidades (id_modulo);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE unidades;
SQL
        );
    }
};
