<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE intentos_evaluacion (
    id_intento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_evaluacion bigint NOT NULL REFERENCES evaluaciones (id_evaluacion) ON DELETE RESTRICT,
    numero_intento integer NOT NULL CHECK (numero_intento > 0),
    fecha_inicio_intento timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin_intento timestamptz ,
    estado_intento varchar(30) NOT NULL DEFAULT 'en_curso' CHECK (estado_intento IN ('en_curso', 'finalizado', 'abandonado')),
    UNIQUE (id_usuario, id_evaluacion, numero_intento),
    UNIQUE (id_intento, id_evaluacion),
    CHECK ((estado_intento = 'en_curso' AND fecha_fin_intento IS NULL) OR (estado_intento IN ('finalizado','abandonado') AND fecha_fin_intento IS NOT NULL AND fecha_fin_intento >= fecha_inicio_intento))
);
CREATE INDEX ix_intentos_evaluacion_id_usuario ON intentos_evaluacion (id_usuario);
CREATE INDEX ix_intentos_evaluacion_id_evaluacion ON intentos_evaluacion (id_evaluacion);
CREATE UNIQUE INDEX uq_intento_abierto ON intentos_evaluacion (id_usuario, id_evaluacion) WHERE estado_intento = 'en_curso';

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE intentos_evaluacion;
SQL
        );
    }
};
