<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE progreso (
    id_progreso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_unidad bigint NOT NULL REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    fecha_inicio_progreso timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion_progreso timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_usuario, id_unidad),
    CHECK (fecha_actualizacion_progreso >= fecha_inicio_progreso)
);
CREATE INDEX ix_progreso_id_usuario ON progreso (id_usuario);
CREATE INDEX ix_progreso_id_unidad ON progreso (id_unidad);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE progreso;
SQL
        );
    }
};
