-- Esquema lógico PostgreSQL 18. En una aplicación Laravel use las migraciones;
-- este archivo permite revisar o crear la base de datos de dominio desde cero.
BEGIN;

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(20) NOT NULL UNIQUE,
    name varchar(50) NOT NULL
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id bigint NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    name varchar(255) NOT NULL,
    cedula varchar(10) UNIQUE CHECK (cedula ~ '^[0-9]{10}$'),
    email varchar(255) NOT NULL UNIQUE,
    email_verified_at timestamp,
    password varchar(255),
    google_id varchar(255) UNIQUE,
    remember_token varchar(100),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    name varchar(80) NOT NULL,
    sort_order integer NOT NULL CHECK (sort_order >= 0),
    is_published boolean NOT NULL DEFAULT true,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE modules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_id bigint NOT NULL REFERENCES levels(id) ON DELETE RESTRICT,
    title varchar(160) NOT NULL,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp
);
CREATE INDEX modules_level_publication_idx ON modules(level_id, is_published, sort_order);

CREATE TABLE units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id bigint NOT NULL REFERENCES modules(id) ON DELETE RESTRICT,
    title varchar(160) NOT NULL,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp
);
CREATE INDEX units_module_publication_idx ON units(module_id, is_published, sort_order);

CREATE TABLE contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id bigint NOT NULL REFERENCES units(id) ON DELETE RESTRICT,
    kind varchar(20) NOT NULL CHECK (kind IN ('vocabulary', 'grammar')),
    title varchar(160) NOT NULL,
    body text NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp
);
CREATE INDEX contents_unit_publication_idx ON contents(unit_id, is_published, sort_order);

CREATE TABLE exercises (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id bigint NOT NULL REFERENCES contents(id) ON DELETE RESTRICT,
    type varchar(20) NOT NULL CHECK (type IN ('multiple_choice', 'complete', 'select')),
    prompt text NOT NULL,
    options jsonb,
    correct_answer text NOT NULL,
    feedback_correct text,
    feedback_incorrect text,
    sort_order integer NOT NULL DEFAULT 0,
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp
);
CREATE INDEX exercises_content_publication_idx ON exercises(content_id, is_published, sort_order);

CREATE TABLE evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_id bigint NOT NULL REFERENCES levels(id) ON DELETE RESTRICT,
    title varchar(160) NOT NULL,
    description text,
    passing_score smallint NOT NULL DEFAULT 70 CHECK (passing_score BETWEEN 0 AND 100),
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp
);
CREATE INDEX evaluations_level_publication_idx ON evaluations(level_id, is_published);

CREATE TABLE evaluation_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id bigint NOT NULL REFERENCES evaluations(id) ON DELETE RESTRICT,
    type varchar(20) NOT NULL CHECK (type IN ('multiple_choice', 'complete', 'select')),
    prompt text NOT NULL,
    options jsonb,
    correct_answer text NOT NULL,
    feedback_correct text,
    feedback_incorrect text,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp,
    updated_at timestamp
);
CREATE INDEX evaluation_questions_order_idx ON evaluation_questions(evaluation_id, sort_order);

CREATE TABLE exercise_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    exercise_id bigint NOT NULL REFERENCES exercises(id) ON DELETE RESTRICT,
    submitted_answer text NOT NULL,
    is_correct boolean NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX exercise_attempts_lookup_idx ON exercise_attempts(user_id, exercise_id, created_at);

CREATE TABLE evaluation_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    evaluation_id bigint NOT NULL REFERENCES evaluations(id) ON DELETE RESTRICT,
    score numeric(5,2) NOT NULL CHECK (score BETWEEN 0 AND 100),
    correct_count integer NOT NULL,
    total_questions integer NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX evaluation_attempts_lookup_idx ON evaluation_attempts(user_id, evaluation_id, created_at);

CREATE TABLE evaluation_attempt_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_attempt_id bigint NOT NULL REFERENCES evaluation_attempts(id) ON DELETE CASCADE,
    evaluation_question_id bigint NOT NULL REFERENCES evaluation_questions(id) ON DELETE RESTRICT,
    submitted_answer text NOT NULL,
    is_correct boolean NOT NULL,
    UNIQUE (evaluation_attempt_id, evaluation_question_id)
);

CREATE TABLE progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    level_id bigint NOT NULL REFERENCES levels(id) ON DELETE RESTRICT,
    exercise_id bigint REFERENCES exercises(id) ON DELETE RESTRICT,
    evaluation_id bigint REFERENCES evaluations(id) ON DELETE RESTRICT,
    best_score numeric(5,2) CHECK (best_score BETWEEN 0 AND 100),
    completed_at timestamp NOT NULL,
    CONSTRAINT progress_one_activity CHECK ((exercise_id IS NOT NULL) <> (evaluation_id IS NOT NULL))
);
CREATE INDEX progress_user_level_idx ON progress(user_id, level_id);
CREATE UNIQUE INDEX progress_exercise_unique ON progress(user_id, exercise_id) WHERE exercise_id IS NOT NULL;
CREATE UNIQUE INDEX progress_evaluation_unique ON progress(user_id, evaluation_id) WHERE evaluation_id IS NOT NULL;

CREATE TABLE testimonials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    body varchar(500) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE glossary (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spanish varchar(160) NOT NULL,
    kichwa varchar(160) NOT NULL,
    meaning text NOT NULL,
    example_spanish text,
    example_kichwa text,
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp,
    UNIQUE (spanish, kichwa)
);
CREATE INDEX glossary_publication_idx ON glossary(is_published);

-- Tabla requerida por Laravel Sanctum. Laravel crea esta tabla con install:api.
CREATE TABLE personal_access_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tokenable_type varchar(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name text NOT NULL,
    token varchar(64) NOT NULL UNIQUE,
    abilities text,
    last_used_at timestamp,
    expires_at timestamp,
    created_at timestamp,
    updated_at timestamp
);
CREATE INDEX personal_access_tokens_tokenable_idx ON personal_access_tokens(tokenable_type, tokenable_id);

INSERT INTO roles (code, name) VALUES ('admin', 'Administrador'), ('student', 'Estudiante');
INSERT INTO levels (code, name, sort_order, is_published, created_at, updated_at)
VALUES ('basic', 'Básico', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('intermediate', 'Intermedio', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT;
