CREATE TABLE usuarios (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula_usuario varchar(20) ,
    nombre_usuario varchar(150) NOT NULL,
    correo_usuario varchar(254) NOT NULL,
    contrasena_usuario varchar(255) NOT NULL,
    rol_usuario varchar(30) NOT NULL DEFAULT 'estudiante' CHECK (rol_usuario IN ('administrador', 'estudiante')),
    estado_usuario varchar(30) NOT NULL DEFAULT 'activo' CHECK (estado_usuario IN ('activo', 'bloqueado')),
    remember_token varchar(100) ,
    UNIQUE (cedula_usuario),
    UNIQUE (correo_usuario),
    CHECK (correo_usuario = lower(btrim(correo_usuario)) AND position('@' in correo_usuario) > 1)
);
