CREATE TABLE niveles (
    id_nivel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_nivel varchar(80) NOT NULL,
    descripcion_nivel text NOT NULL,
    orden_nivel integer NOT NULL CHECK (orden_nivel > 0),
    UNIQUE (nombre_nivel),
    UNIQUE (orden_nivel)
);
