CREATE TABLE usuarios_niveles (
    id_usuario_nivel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_nivel bigint NOT NULL REFERENCES niveles (id_nivel) ON DELETE RESTRICT,
    UNIQUE (id_usuario, id_nivel)
);
CREATE INDEX ix_usuarios_niveles_id_usuario ON usuarios_niveles (id_usuario);
CREATE INDEX ix_usuarios_niveles_id_nivel ON usuarios_niveles (id_nivel);
