CREATE TABLE actividades (
    id_actividad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad bigint NOT NULL REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    tipo_actividad varchar(30) NOT NULL CHECK (tipo_actividad IN ('seleccion_multiple', 'completar', 'relacionar', 'arrastrar')),
    enunciado_actividad text NOT NULL,
    elementos_actividad jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(elementos_actividad) = 'array'),
    zonas_actividad jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(zonas_actividad) = 'array'),
    recurso_actividad varchar(500) ,
    solucion_actividad jsonb NOT NULL CHECK (jsonb_typeof(solucion_actividad) = 'object'),
    orden_actividad integer NOT NULL CHECK (orden_actividad > 0),
    UNIQUE (id_unidad, orden_actividad)
);
CREATE INDEX ix_actividades_id_unidad ON actividades (id_unidad);
