CREATE TABLE evaluaciones (
    id_evaluacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad bigint REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    titulo_evaluacion varchar(180) NOT NULL,
    tipo_evaluacion varchar(30) NOT NULL CHECK (tipo_evaluacion IN ('unidad', 'diagnostica')),
    CHECK ((tipo_evaluacion = 'unidad' AND id_unidad IS NOT NULL) OR (tipo_evaluacion = 'diagnostica' AND id_unidad IS NULL))
);
CREATE INDEX ix_evaluaciones_id_unidad ON evaluaciones (id_unidad);
