CREATE TABLE preguntas (
    id_pregunta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evaluacion bigint NOT NULL REFERENCES evaluaciones (id_evaluacion) ON DELETE RESTRICT,
    tipo_pregunta varchar(30) NOT NULL CHECK (tipo_pregunta IN ('seleccion_multiple', 'completar', 'relacionar', 'arrastrar')),
    enunciado_pregunta text NOT NULL,
    elementos_pregunta jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(elementos_pregunta) = 'array'),
    zonas_pregunta jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(zonas_pregunta) = 'array'),
    recurso_pregunta varchar(500) ,
    solucion_pregunta jsonb NOT NULL CHECK (jsonb_typeof(solucion_pregunta) = 'object'),
    puntaje_pregunta numeric(8,2) NOT NULL CHECK (puntaje_pregunta > 0),
    orden_pregunta integer NOT NULL CHECK (orden_pregunta > 0),
    UNIQUE (id_evaluacion, orden_pregunta),
    UNIQUE (id_pregunta, id_evaluacion)
);
CREATE INDEX ix_preguntas_id_evaluacion ON preguntas (id_evaluacion);
