CREATE TABLE respuestas_evaluacion (
    id_respuesta_evaluacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_intento bigint NOT NULL,
    id_pregunta bigint NOT NULL,
    id_evaluacion bigint NOT NULL,
    respuesta_evaluacion jsonb NOT NULL CHECK (jsonb_typeof(respuesta_evaluacion) = 'object'),
    puntaje_respuesta_evaluacion numeric(8,2) NOT NULL CHECK (puntaje_respuesta_evaluacion >= 0),
    fecha_respuesta_evaluacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_intento, id_pregunta),
    FOREIGN KEY (id_intento, id_evaluacion) REFERENCES intentos_evaluacion (id_intento, id_evaluacion) ON DELETE RESTRICT,
    FOREIGN KEY (id_pregunta, id_evaluacion) REFERENCES preguntas (id_pregunta, id_evaluacion) ON DELETE RESTRICT
);
CREATE INDEX ix_respuestas_evaluacion_id_intento ON respuestas_evaluacion (id_intento);
CREATE INDEX ix_respuestas_evaluacion_id_pregunta ON respuestas_evaluacion (id_pregunta);
