CREATE TABLE diccionario (
    id_diccionario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palabra_kichwa_diccionario varchar(200) NOT NULL,
    palabra_espanol_diccionario varchar(250) NOT NULL,
    UNIQUE (palabra_kichwa_diccionario, palabra_espanol_diccionario)
);
