-- Alternativa a Artisan; NO ejecutar ambas rutas en la misma base.
BEGIN;
CREATE TABLE usuarios (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula_usuario varchar(20) ,
    nombre_usuario varchar(150) NOT NULL,
    correo_usuario varchar(254) NOT NULL,
    contrasena_usuario varchar(255) NOT NULL,
    rol_usuario varchar(30) NOT NULL DEFAULT 'estudiante' CHECK (rol_usuario IN ('administrador', 'estudiante')),
    estado_usuario varchar(30) NOT NULL DEFAULT 'activo' CHECK (estado_usuario IN ('activo', 'bloqueado')),
    remember_token varchar(100) ,
    UNIQUE (cedula_usuario),
    UNIQUE (correo_usuario),
    CHECK (correo_usuario = lower(btrim(correo_usuario)) AND position('@' in correo_usuario) > 1)
);

CREATE TABLE niveles (
    id_nivel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_nivel varchar(80) NOT NULL,
    descripcion_nivel text NOT NULL,
    orden_nivel integer NOT NULL CHECK (orden_nivel > 0),
    UNIQUE (nombre_nivel),
    UNIQUE (orden_nivel)
);

CREATE TABLE modulos (
    id_modulo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nivel bigint NOT NULL REFERENCES niveles (id_nivel) ON DELETE RESTRICT,
    nombre_modulo varchar(150) NOT NULL,
    descripcion_modulo text NOT NULL,
    orden_modulo integer NOT NULL CHECK (orden_modulo > 0),
    UNIQUE (id_nivel, orden_modulo)
);
CREATE INDEX ix_modulos_id_nivel ON modulos (id_nivel);

CREATE TABLE unidades (
    id_unidad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_modulo bigint NOT NULL REFERENCES modulos (id_modulo) ON DELETE RESTRICT,
    titulo_unidad varchar(180) NOT NULL,
    objetivo_unidad text NOT NULL,
    orden_unidad integer NOT NULL CHECK (orden_unidad > 0),
    UNIQUE (id_modulo, orden_unidad)
);
CREATE INDEX ix_unidades_id_modulo ON unidades (id_modulo);

CREATE TABLE usuarios_niveles (
    id_usuario_nivel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_nivel bigint NOT NULL REFERENCES niveles (id_nivel) ON DELETE RESTRICT,
    UNIQUE (id_usuario, id_nivel)
);
CREATE INDEX ix_usuarios_niveles_id_usuario ON usuarios_niveles (id_usuario);
CREATE INDEX ix_usuarios_niveles_id_nivel ON usuarios_niveles (id_nivel);

CREATE TABLE progreso (
    id_progreso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_unidad bigint NOT NULL REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    fecha_inicio_progreso timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion_progreso timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_usuario, id_unidad),
    CHECK (fecha_actualizacion_progreso >= fecha_inicio_progreso)
);
CREATE INDEX ix_progreso_id_usuario ON progreso (id_usuario);
CREATE INDEX ix_progreso_id_unidad ON progreso (id_unidad);

CREATE TABLE temas (
    id_tema bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad bigint NOT NULL REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    tipo_tema varchar(30) NOT NULL CHECK (tipo_tema IN ('vocabulario', 'gramatica', 'cultura')),
    titulo_tema varchar(180) NOT NULL,
    contenido_tema text NOT NULL,
    orden_tema integer NOT NULL CHECK (orden_tema > 0),
    UNIQUE (id_unidad, orden_tema)
);
CREATE INDEX ix_temas_id_unidad ON temas (id_unidad);

CREATE TABLE actividades (
    id_actividad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad bigint NOT NULL REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    tipo_actividad varchar(30) NOT NULL CHECK (tipo_actividad IN ('seleccion_multiple', 'completar', 'relacionar', 'arrastrar')),
    enunciado_actividad text NOT NULL,
    elementos_actividad jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(elementos_actividad) = 'array'),
    zonas_actividad jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(zonas_actividad) = 'array'),
    recurso_actividad varchar(500) ,
    solucion_actividad jsonb NOT NULL CHECK (jsonb_typeof(solucion_actividad) = 'object'),
    orden_actividad integer NOT NULL CHECK (orden_actividad > 0),
    UNIQUE (id_unidad, orden_actividad)
);
CREATE INDEX ix_actividades_id_unidad ON actividades (id_unidad);

CREATE TABLE respuestas_actividad (
    id_respuesta_actividad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_actividad bigint NOT NULL REFERENCES actividades (id_actividad) ON DELETE RESTRICT,
    respuesta_actividad jsonb NOT NULL CHECK (jsonb_typeof(respuesta_actividad) = 'object'),
    acierto_actividad boolean NOT NULL,
    retroalimentacion_actividad text NOT NULL,
    fecha_respuesta_actividad timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_respuestas_actividad_id_usuario ON respuestas_actividad (id_usuario);
CREATE INDEX ix_respuestas_actividad_id_actividad ON respuestas_actividad (id_actividad);

CREATE TABLE evaluaciones (
    id_evaluacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad bigint REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    titulo_evaluacion varchar(180) NOT NULL,
    tipo_evaluacion varchar(30) NOT NULL CHECK (tipo_evaluacion IN ('unidad', 'diagnostica')),
    CHECK ((tipo_evaluacion = 'unidad' AND id_unidad IS NOT NULL) OR (tipo_evaluacion = 'diagnostica' AND id_unidad IS NULL))
);
CREATE INDEX ix_evaluaciones_id_unidad ON evaluaciones (id_unidad);

CREATE TABLE preguntas (
    id_pregunta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evaluacion bigint NOT NULL REFERENCES evaluaciones (id_evaluacion) ON DELETE RESTRICT,
    tipo_pregunta varchar(30) NOT NULL CHECK (tipo_pregunta IN ('seleccion_multiple', 'completar', 'relacionar', 'arrastrar')),
    enunciado_pregunta text NOT NULL,
    elementos_pregunta jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(elementos_pregunta) = 'array'),
    zonas_pregunta jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(zonas_pregunta) = 'array'),
    recurso_pregunta varchar(500) ,
    solucion_pregunta jsonb NOT NULL CHECK (jsonb_typeof(solucion_pregunta) = 'object'),
    puntaje_pregunta numeric(8,2) NOT NULL CHECK (puntaje_pregunta > 0),
    orden_pregunta integer NOT NULL CHECK (orden_pregunta > 0),
    UNIQUE (id_evaluacion, orden_pregunta),
    UNIQUE (id_pregunta, id_evaluacion)
);
CREATE INDEX ix_preguntas_id_evaluacion ON preguntas (id_evaluacion);

CREATE TABLE intentos_evaluacion (
    id_intento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_evaluacion bigint NOT NULL REFERENCES evaluaciones (id_evaluacion) ON DELETE RESTRICT,
    numero_intento integer NOT NULL CHECK (numero_intento > 0),
    fecha_inicio_intento timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin_intento timestamptz ,
    estado_intento varchar(30) NOT NULL DEFAULT 'en_curso' CHECK (estado_intento IN ('en_curso', 'finalizado', 'abandonado')),
    UNIQUE (id_usuario, id_evaluacion, numero_intento),
    UNIQUE (id_intento, id_evaluacion),
    CHECK ((estado_intento = 'en_curso' AND fecha_fin_intento IS NULL) OR (estado_intento IN ('finalizado','abandonado') AND fecha_fin_intento IS NOT NULL AND fecha_fin_intento >= fecha_inicio_intento))
);
CREATE INDEX ix_intentos_evaluacion_id_usuario ON intentos_evaluacion (id_usuario);
CREATE INDEX ix_intentos_evaluacion_id_evaluacion ON intentos_evaluacion (id_evaluacion);
CREATE UNIQUE INDEX uq_intento_abierto ON intentos_evaluacion (id_usuario, id_evaluacion) WHERE estado_intento = 'en_curso';

CREATE TABLE respuestas_evaluacion (
    id_respuesta_evaluacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_intento bigint NOT NULL,
    id_pregunta bigint NOT NULL,
    id_evaluacion bigint NOT NULL,
    respuesta_evaluacion jsonb NOT NULL CHECK (jsonb_typeof(respuesta_evaluacion) = 'object'),
    puntaje_respuesta_evaluacion numeric(8,2) NOT NULL CHECK (puntaje_respuesta_evaluacion >= 0),
    fecha_respuesta_evaluacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_intento, id_pregunta),
    FOREIGN KEY (id_intento, id_evaluacion) REFERENCES intentos_evaluacion (id_intento, id_evaluacion) ON DELETE RESTRICT,
    FOREIGN KEY (id_pregunta, id_evaluacion) REFERENCES preguntas (id_pregunta, id_evaluacion) ON DELETE RESTRICT
);
CREATE INDEX ix_respuestas_evaluacion_id_intento ON respuestas_evaluacion (id_intento);
CREATE INDEX ix_respuestas_evaluacion_id_pregunta ON respuestas_evaluacion (id_pregunta);

CREATE TABLE diccionario (
    id_diccionario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palabra_kichwa_diccionario varchar(200) NOT NULL,
    palabra_espanol_diccionario varchar(250) NOT NULL,
    UNIQUE (palabra_kichwa_diccionario, palabra_espanol_diccionario)
);

-- Reglas entre filas que no pueden expresarse mediante CHECK.
CREATE FUNCTION kichwa_validar_estudiante() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM usuarios WHERE id_usuario = NEW.id_usuario AND rol_usuario = 'estudiante' FOR SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION 'La participación requiere un estudiante' USING ERRCODE = '23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER estudiante_nivel BEFORE INSERT OR UPDATE ON usuarios_niveles FOR EACH ROW EXECUTE FUNCTION kichwa_validar_estudiante();
CREATE TRIGGER estudiante_progreso BEFORE INSERT OR UPDATE ON progreso FOR EACH ROW EXECUTE FUNCTION kichwa_validar_estudiante();
CREATE TRIGGER estudiante_actividad BEFORE INSERT OR UPDATE ON respuestas_actividad FOR EACH ROW EXECUTE FUNCTION kichwa_validar_estudiante();
CREATE TRIGGER estudiante_intento BEFORE INSERT OR UPDATE ON intentos_evaluacion FOR EACH ROW EXECUTE FUNCTION kichwa_validar_estudiante();

CREATE FUNCTION kichwa_proteger_rol() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.rol_usuario <> OLD.rol_usuario AND (
      EXISTS (SELECT 1 FROM usuarios_niveles WHERE id_usuario=OLD.id_usuario) OR
      EXISTS (SELECT 1 FROM progreso WHERE id_usuario=OLD.id_usuario) OR
      EXISTS (SELECT 1 FROM respuestas_actividad WHERE id_usuario=OLD.id_usuario) OR
      EXISTS (SELECT 1 FROM intentos_evaluacion WHERE id_usuario=OLD.id_usuario))
    THEN RAISE EXCEPTION 'No cambie el rol de un estudiante con historial' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER proteger_rol BEFORE UPDATE ON usuarios FOR EACH ROW EXECUTE FUNCTION kichwa_proteger_rol();

CREATE FUNCTION kichwa_proteger_pregunta() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE anterior bigint; actual bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN anterior := OLD.id_evaluacion; END IF;
    IF TG_OP <> 'DELETE' THEN actual := NEW.id_evaluacion; END IF;
    PERFORM id_evaluacion FROM evaluaciones WHERE id_evaluacion IN (anterior, actual) ORDER BY id_evaluacion FOR UPDATE;
    IF EXISTS (SELECT 1 FROM intentos_evaluacion WHERE id_evaluacion IN (anterior, actual)) THEN
      RAISE EXCEPTION 'Evaluación utilizada: cree otra versión antes de cambiar sus preguntas' USING ERRCODE='23514';
    END IF;
    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER proteger_pregunta BEFORE INSERT OR UPDATE OR DELETE ON preguntas FOR EACH ROW EXECUTE FUNCTION kichwa_proteger_pregunta();

CREATE FUNCTION kichwa_proteger_evaluacion() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM intentos_evaluacion WHERE id_evaluacion=OLD.id_evaluacion) THEN
      RAISE EXCEPTION 'Evaluación con historial: no se permite modificarla o eliminarla' USING ERRCODE='23514';
    END IF;
    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER proteger_evaluacion BEFORE UPDATE OR DELETE ON evaluaciones FOR EACH ROW EXECUTE FUNCTION kichwa_proteger_evaluacion();

CREATE FUNCTION kichwa_validar_intento() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='UPDATE' THEN
      IF OLD.estado_intento <> 'en_curso' THEN RAISE EXCEPTION 'El intento cerrado es inmutable' USING ERRCODE='23514'; END IF;
      IF (NEW.id_usuario,NEW.id_evaluacion,NEW.numero_intento,NEW.fecha_inicio_intento,NEW.id_intento)
         IS DISTINCT FROM (OLD.id_usuario,OLD.id_evaluacion,OLD.numero_intento,OLD.fecha_inicio_intento,OLD.id_intento)
      THEN RAISE EXCEPTION 'No cambie la identidad del intento' USING ERRCODE='23514'; END IF;
      IF NEW.fecha_fin_intento < (SELECT max(fecha_respuesta_evaluacion) FROM respuestas_evaluacion WHERE id_intento=OLD.id_intento)
      THEN RAISE EXCEPTION 'El cierre no puede preceder a las respuestas' USING ERRCODE='23514'; END IF;
    ELSE
      IF NEW.estado_intento <> 'en_curso' THEN RAISE EXCEPTION 'Un intento debe comenzar en curso' USING ERRCODE='23514'; END IF;
    END IF;
    PERFORM 1 FROM evaluaciones WHERE id_evaluacion=NEW.id_evaluacion FOR UPDATE;
    IF NOT EXISTS (SELECT 1 FROM preguntas WHERE id_evaluacion=NEW.id_evaluacion)
    THEN RAISE EXCEPTION 'No se puede iniciar una evaluación sin preguntas' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER validar_intento BEFORE INSERT OR UPDATE ON intentos_evaluacion FOR EACH ROW EXECUTE FUNCTION kichwa_validar_intento();

CREATE FUNCTION kichwa_validar_respuesta_evaluacion() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE intento intentos_evaluacion%ROWTYPE; maximo numeric; destino bigint;
BEGIN
    IF TG_OP='DELETE' THEN destino:=OLD.id_intento; ELSE destino:=NEW.id_intento; END IF;
    SELECT * INTO intento FROM intentos_evaluacion WHERE id_intento=destino FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Intento inexistente' USING ERRCODE='23503'; END IF;
    IF intento.estado_intento <> 'en_curso' THEN RAISE EXCEPTION 'No se puede cambiar una respuesta de un intento cerrado' USING ERRCODE='23514'; END IF;
    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    IF TG_OP='UPDATE' AND (NEW.id_intento,NEW.id_pregunta,NEW.id_evaluacion,NEW.id_respuesta_evaluacion)
       IS DISTINCT FROM (OLD.id_intento,OLD.id_pregunta,OLD.id_evaluacion,OLD.id_respuesta_evaluacion)
    THEN RAISE EXCEPTION 'La identidad de la respuesta es inmutable' USING ERRCODE='23514'; END IF;
    SELECT puntaje_pregunta INTO maximo FROM preguntas WHERE id_pregunta=NEW.id_pregunta AND id_evaluacion=NEW.id_evaluacion;
    IF maximo IS NULL OR intento.id_evaluacion <> NEW.id_evaluacion THEN RAISE EXCEPTION 'La pregunta no pertenece a la evaluación del intento' USING ERRCODE='23503'; END IF;
    IF NEW.puntaje_respuesta_evaluacion > maximo THEN RAISE EXCEPTION 'Puntaje superior al máximo de la pregunta' USING ERRCODE='23514'; END IF;
    IF NEW.fecha_respuesta_evaluacion < intento.fecha_inicio_intento THEN RAISE EXCEPTION 'La respuesta no puede preceder al intento' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER validar_respuesta_evaluacion BEFORE INSERT OR UPDATE OR DELETE ON respuestas_evaluacion FOR EACH ROW EXECUTE FUNCTION kichwa_validar_respuesta_evaluacion();

CREATE FUNCTION kichwa_proteger_actividad() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM respuestas_actividad WHERE id_actividad=OLD.id_actividad) THEN
      RAISE EXCEPTION 'Actividad con respuestas: cree una nueva versión' USING ERRCODE='23514';
    END IF;
    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER proteger_actividad BEFORE UPDATE OR DELETE ON actividades FOR EACH ROW EXECUTE FUNCTION kichwa_proteger_actividad();

CREATE FUNCTION kichwa_registrar_practica() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE unidad bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Las respuestas de práctica son históricas; registre otro envío' USING ERRCODE='23514'; END IF;
    SELECT id_unidad INTO unidad FROM actividades WHERE id_actividad=NEW.id_actividad FOR UPDATE;
    IF unidad IS NULL THEN RAISE EXCEPTION 'Actividad inexistente' USING ERRCODE='23503'; END IF;
    INSERT INTO progreso (id_usuario,id_unidad,fecha_inicio_progreso,fecha_actualizacion_progreso)
    VALUES (NEW.id_usuario,unidad,NEW.fecha_respuesta_actividad,NEW.fecha_respuesta_actividad)
    ON CONFLICT (id_usuario,id_unidad) DO UPDATE SET
      fecha_inicio_progreso=LEAST(progreso.fecha_inicio_progreso,EXCLUDED.fecha_inicio_progreso),
      fecha_actualizacion_progreso=GREATEST(progreso.fecha_actualizacion_progreso,EXCLUDED.fecha_actualizacion_progreso);
    RETURN NEW;
END;
$$;
CREATE TRIGGER registrar_practica BEFORE INSERT OR UPDATE OR DELETE ON respuestas_actividad FOR EACH ROW EXECUTE FUNCTION kichwa_registrar_practica();

CREATE VIEW v_evaluaciones AS
SELECT e.*, COALESCE(p.puntaje_maximo_evaluacion,0)::numeric(12,2) AS puntaje_maximo_evaluacion
FROM evaluaciones e LEFT JOIN (
 SELECT id_evaluacion, sum(puntaje_pregunta) AS puntaje_maximo_evaluacion FROM preguntas GROUP BY id_evaluacion
) p USING (id_evaluacion);

CREATE VIEW v_intentos_evaluacion AS
SELECT i.*, COALESCE(r.puntaje_obtenido,0)::numeric(12,2) AS puntaje_obtenido,
       e.puntaje_maximo_evaluacion,
       CASE WHEN i.estado_intento='finalizado' THEN COALESCE(r.puntaje_obtenido,0)::numeric(12,2) ELSE NULL END AS calificacion_intento,
       CASE WHEN i.estado_intento='finalizado' AND e.puntaje_maximo_evaluacion>0
         THEN round(100*COALESCE(r.puntaje_obtenido,0)/e.puntaje_maximo_evaluacion,2) ELSE NULL END AS porcentaje_calificacion
FROM intentos_evaluacion i JOIN v_evaluaciones e USING (id_evaluacion)
LEFT JOIN (SELECT id_intento,sum(puntaje_respuesta_evaluacion) AS puntaje_obtenido FROM respuestas_evaluacion GROUP BY id_intento) r USING (id_intento);

-- Decisión de implementación: avance de práctica = actividades distintas acertadas / total.
-- No es un criterio pedagógico validado ni una nota de evaluación.
CREATE VIEW v_progreso AS
SELECT p.*, COALESCE(a.total_actividades,0) AS total_actividades,
       COALESCE(r.actividades_completadas,0) AS actividades_completadas,
       CASE WHEN COALESCE(a.total_actividades,0)=0 THEN 0::numeric
         ELSE round(100.0*COALESCE(r.actividades_completadas,0)/a.total_actividades,2) END AS porcentaje_progreso,
       CASE WHEN COALESCE(a.total_actividades,0)>0 AND COALESCE(r.actividades_completadas,0)=a.total_actividades
         THEN 'completado' ELSE 'en_curso' END::varchar(30) AS estado_progreso
FROM progreso p
LEFT JOIN (SELECT id_unidad,count(*) AS total_actividades FROM actividades GROUP BY id_unidad) a USING(id_unidad)
LEFT JOIN (SELECT r.id_usuario,a.id_unidad,count(DISTINCT r.id_actividad) AS actividades_completadas
 FROM respuestas_actividad r JOIN actividades a USING(id_actividad) WHERE r.acierto_actividad GROUP BY r.id_usuario,a.id_unidad) r
 ON r.id_usuario=p.id_usuario AND r.id_unidad=p.id_unidad;

-- Incluye unidades aún no iniciadas con 0; no promedia sólo lo que el estudiante comenzó.
CREATE VIEW v_progreso_modulos AS
SELECT un.id_usuario,m.id_modulo,m.id_nivel,
 COALESCE(round(avg(COALESCE(p.porcentaje_progreso,0)),2),0) AS porcentaje_progreso_modulo
FROM usuarios_niveles un JOIN modulos m ON m.id_nivel=un.id_nivel
LEFT JOIN unidades u ON u.id_modulo=m.id_modulo
LEFT JOIN v_progreso p ON p.id_usuario=un.id_usuario AND p.id_unidad=u.id_unidad
GROUP BY un.id_usuario,m.id_modulo,m.id_nivel;

CREATE VIEW v_progreso_niveles AS
SELECT un.id_usuario,un.id_nivel,
 COALESCE(round(avg(COALESCE(p.porcentaje_progreso,0)) FILTER (WHERE u.id_unidad IS NOT NULL),2),0) AS porcentaje_progreso_nivel
FROM usuarios_niveles un LEFT JOIN modulos m ON m.id_nivel=un.id_nivel
LEFT JOIN unidades u ON u.id_modulo=m.id_modulo
LEFT JOIN v_progreso p ON p.id_usuario=un.id_usuario AND p.id_unidad=u.id_unidad
GROUP BY un.id_usuario,un.id_nivel;

COMMIT;
