<?php

namespace Tests\Feature;

use App\Models\Diccionario;
use App\Models\Usuario;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Laravel\Sanctum\Sanctum;
use PHPUnit\Framework\Attributes\TestWith;
use Tests\TestCase;
use Tests\UsesPostgreSQL;

class DictionarySearchTest extends TestCase
{
    use UsesPostgreSQL;

    public function test_migration_preserves_translations_and_unifies_legacy_entries(): void
    {
        Schema::drop('diccionario');
        $original = require database_path('migrations/2026_09_30_000014_create_diccionario_table.php');
        $original->up();
        DB::statement('ALTER TABLE diccionario ADD COLUMN sinonimos_diccionario text, ADD COLUMN notas_diccionario text');
        DB::table('diccionario')->insert(['palabra_kichwa_diccionario' => '[DEMO] original', 'palabra_espanol_diccionario' => 'Traducción original', 'notas_diccionario' => 'Retirar']);
        $id = DB::table('diccionario')->value('id_diccionario');
        DB::statement('CREATE TABLE glossary (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kichwa varchar(160), spanish varchar(160))');
        DB::table('glossary')->insert([
            ['kichwa' => '[DEMO] original', 'spanish' => 'Traducción original'],
            ['kichwa' => '[DEMO] anterior', 'spanish' => 'Traducción anterior'],
        ]);

        $migration = require database_path('migrations/2026_10_06_163017_simplify_diccionario_and_remove_legacy_glossary.php');
        $migration->up();

        $this->assertSame(['id', 'kichwa', 'español'], Schema::getColumnListing('diccionario'));
        $this->assertFalse(Schema::hasTable('glossary'));
        $this->assertDatabaseCount('diccionario', 2);
        $this->assertDatabaseHas('diccionario', ['id' => $id, 'kichwa' => '[DEMO] original', 'español' => 'Traducción original']);
        $this->assertDatabaseHas('diccionario', ['kichwa' => '[DEMO] anterior', 'español' => 'Traducción anterior']);
    }

    public function test_admin_can_create_edit_list_and_delete_three_field_entries(): void
    {
        $this->postJson('/api/admin/diccionario', ['kichwa' => '[DEMO] entrada', 'español' => 'Traducción'])->assertUnauthorized();
        Sanctum::actingAs(Usuario::factory()->create());
        $this->postJson('/api/admin/diccionario', ['kichwa' => '[DEMO] entrada', 'español' => 'Traducción'])->assertForbidden();
        Sanctum::actingAs(Usuario::factory()->administrador()->create());
        $this->postJson('/api/admin/diccionario', ['kichwa' => ''])->assertUnprocessable()->assertJsonValidationErrors(['kichwa', 'español']);
        $response = $this->postJson('/api/admin/diccionario', ['kichwa' => '[DEMO] entrada', 'español' => 'Traducción', 'id' => 999999, 'notes' => 'No guardar'])->assertCreated();
        $id = $response->json('id');
        $this->assertNotSame(999999, $id);
        $response->assertExactJson(['id' => $id, 'kichwa' => '[DEMO] entrada', 'español' => 'Traducción']);
        $this->assertDatabaseHas('diccionario', ['id' => $id, 'kichwa' => '[DEMO] entrada', 'español' => 'Traducción']);
        $this->getJson('/api/admin/overview')->assertOk()->assertJsonPath('diccionario', 1)->assertJsonMissingPath('glossary');
        $this->getJson('/api/admin/diccionario')->assertOk()->assertJsonPath('data.0', ['id' => $id, 'kichwa' => '[DEMO] entrada', 'español' => 'Traducción']);
        $this->patchJson('/api/admin/diccionario/'.$id, ['español' => 'Corregida'])->assertOk()->assertExactJson(['id' => $id, 'kichwa' => '[DEMO] entrada', 'español' => 'Corregida']);
        $this->assertDatabaseHas('diccionario', ['id' => $id, 'español' => 'Corregida']);
        $this->postJson('/api/admin/diccionario', ['kichwa' => '[DEMO] entrada', 'español' => 'Corregida'])->assertUnprocessable()->assertJsonValidationErrors('kichwa');
        $this->deleteJson('/api/admin/diccionario/'.$id)->assertNoContent();
        $this->assertDatabaseMissing('diccionario', ['id' => $id]);
    }

    public function test_csv_rejects_extra_and_duplicate_headers_without_importing_entries(): void
    {
        Sanctum::actingAs(Usuario::factory()->administrador()->create());
        foreach (["kichwa,español,notes\nentrada,traducción,nota\n", "kichwa,kichwa\nentrada,traducción\n", "kichwa,español,español\nentrada,traducción,otra\n"] as $csv) {
            $this->postJson('/api/admin/diccionario/import', ['file' => UploadedFile::fake()->createWithContent('entrada.csv', $csv)])->assertUnprocessable()->assertJsonValidationErrors('file');
        }
        $this->assertDatabaseCount('diccionario', 0);
    }

    public function test_csv_supports_bom_semicolons_and_reversed_headers(): void
    {
        Sanctum::actingAs(Usuario::factory()->administrador()->create());
        $csv = "\xEF\xBB\xBFespañol;kichwa\nTraducción;[DEMO] entrada\n";
        $this->postJson('/api/admin/diccionario/import', ['file' => UploadedFile::fake()->createWithContent('entrada.csv', $csv)])->assertCreated()->assertJsonPath('inserted', 1);
        $this->assertDatabaseHas('diccionario', ['kichwa' => '[DEMO] entrada', 'español' => 'Traducción']);
    }

    public function test_demo_csv_is_rejected_outside_local_and_testing(): void
    {
        Sanctum::actingAs(Usuario::factory()->administrador()->create());
        $original = app()->environment();
        app()->detectEnvironment(fn () => 'production');
        try {
            $this->postJson('/api/admin/diccionario/import', ['file' => UploadedFile::fake()->createWithContent('entrada.csv', "kichwa,español\n[DEMO] prueba,entrada\n")])->assertUnprocessable()->assertJsonValidationErrors('file');
            $this->assertDatabaseCount('diccionario', 0);
        } finally {
            app()->detectEnvironment(fn () => $original);
        }
    }

    public function test_direction_accents_prefix_priority_and_only_dictionary_fields_are_returned(): void
    {
        Diccionario::create(['kichwa' => 'xábc', 'español' => 'Otra entrada técnica']);
        $first = Diccionario::create(['kichwa' => 'Ábc inicial', 'español' => 'Éxito técnico']);
        $this->getJson('/api/diccionario/buscar?q=ABC&direccion=kichwa-es')->assertOk()->assertJsonPath('total', 2)->assertJsonPath('data.0', ['id' => $first->id, 'kichwa' => 'Ábc inicial', 'español' => 'Éxito técnico']);
        $this->getJson('/api/diccionario/buscar?q=exito&direccion=es-kichwa')->assertOk()->assertJsonPath('total', 1)->assertJsonPath('data.0.kichwa', 'Ábc inicial');
        $this->getJson('/api/diccionario/buscar?q=%25&direccion=es-kichwa')->assertOk()->assertJsonPath('total', 0);
        $this->getJson('/api/diccionario/buscar?q=x&direccion=invalid')->assertUnprocessable()->assertJsonValidationErrors('direccion');
    }

    #[TestWith([' AGUA ', [['kunuk yaku', 's. agua termal.'], ['pallta', 's. aguacate.'], ['yaku', 's. agua, líquido; s. octubre.']], ['yaku', 'kunuk yaku', 'pallta']])]
    #[TestWith(['casa', [['wasiyuk', 'dueño de casa.'], ['sawarishka', 'casado, -da.'], ['wasi', 's. casa, vivienda.']], ['wasi', 'wasiyuk', 'sawarishka']])]
    #[TestWith(['sol', [['kaspiyashka', 'sólido.'], ['inti', 's. sol; junio.'], ['intiyay', 'salir el sol.']], ['inti', 'intiyay', 'kaspiyashka']])]
    #[TestWith(['madre', [['mamantin', 's. madre e hijo.'], ['chukuri', 's. variedad de comadreja; ardilla.'], ['mama', 's. mamá, madre, señora; doña, matrona; grande.']], ['mama', 'mamantin', 'chukuri']])]
    #[TestWith(['niño', [['uchilla', 'adj. pequeño; Niño.'], ['chakpa', 's. niño que nace de pie.'], ['wawa', 's. niño, bebé; adj. pequeño.']], ['wawa', 'uchilla', 'chakpa']])]
    #[TestWith(['agua de regadio', [['parkuy', 'esparcir — agua de regadío.'], ['parku yaku', '(¿?), s. agua de regadío; líquido.']], ['parku yaku', 'parkuy']])]
    #[TestWith(['langosta', [['otro', 's. insecto; langosta.'], ['aharway', '(¿?), s. langosta.']], ['aharway', 'otro']])]
    #[TestWith(['agua', [['tallina', 'v. regar, esparcir; verter, regar agua; desbordarse.'], ['kunuk yaku', 's. agua termal.'], ['yaku', 's. agua, líquido; s. octubre.']], ['yaku', 'tallina', 'kunuk yaku']])]
    public function test_spanish_search_ranks_individual_dictionary_meanings_before_related_phrases_and_substrings(string $word, array $definitions, array $expected): void
    {
        foreach ($definitions as [$kichwa, $spanish]) {
            Diccionario::create(['kichwa' => $kichwa, 'español' => $spanish]);
        }

        $response = $this->getJson('/api/diccionario/buscar?'.http_build_query(['q' => $word, 'direccion' => 'es-kichwa']))->assertOk();

        $this->assertSame($expected, array_column($response->json('data'), 'kichwa'));
    }

    public function test_spanish_exact_meaning_is_on_first_page_even_after_many_related_entries(): void
    {
        foreach (range(1, 25) as $index) {
            Diccionario::create(['kichwa' => 'relacionada '.$index, 'español' => 's. agua termal.']);
        }
        $exact = Diccionario::create(['kichwa' => 'yaku', 'español' => 's. agua, líquido; s. octubre.']);

        $first = $this->getJson('/api/diccionario/buscar?q=agua&direccion=es-kichwa')->assertOk()->assertJsonPath('total', 26)->assertJsonPath('data.0.id', $exact->id);
        $second = $this->getJson('/api/diccionario/buscar?q=agua&direccion=es-kichwa&page=2')->assertOk()->assertJsonCount(6, 'data');

        $ids = array_merge(array_column($first->json('data'), 'id'), array_column($second->json('data'), 'id'));
        $this->assertCount(26, array_unique($ids));
    }

    #[TestWith(['kichwa-es', 'kichwa', 'español'])]
    #[TestWith(['es-kichwa', 'español', 'kichwa'])]
    public function test_exact_matches_come_first_and_similarity_outweighs_prefix_position(string $direction, string $source, string $target): void
    {
        $entries = [];
        foreach (['a abc expresión larga adicional', 'abc a expresión larga adicional', 'xabc', 'abc z', '  Ábc  '] as $index => $word) {
            $entries[$word] = Diccionario::create([$source => $word, $target => 'Traducción '.$index]);
        }

        $response = $this->getJson('/api/diccionario/buscar?'.http_build_query(['q' => '  ABC  ', 'direccion' => $direction]))->assertOk()->assertJsonPath('total', 5);

        $this->assertSame([
            $entries['  Ábc  ']->id,
            $entries['abc z']->id,
            ...($direction === 'kichwa-es' ? [$entries['xabc']->id] : []),
            $entries['abc a expresión larga adicional']->id,
            $entries['a abc expresión larga adicional']->id,
            ...($direction === 'es-kichwa' ? [$entries['xabc']->id] : []),
        ], array_column($response->json('data'), 'id'));
        $response->assertJsonPath('data.0.'.$target, 'Traducción 4');
    }

    #[TestWith(['kichwa-es', 'kichwa', 'español'])]
    #[TestWith(['es-kichwa', 'español', 'kichwa'])]
    public function test_exact_match_stays_on_first_page_and_equal_matches_paginate_stably(string $direction, string $source, string $target): void
    {
        $prefixes = [];
        foreach (range(1, 25) as $index) {
            $prefixes[] = Diccionario::create([$source => 'abc similar', $target => 'Traducción '.$index])->id;
        }
        $exact = Diccionario::create([$source => 'Ábc', $target => 'Exacta']);

        $first = $this->getJson('/api/diccionario/buscar?q=abc&direccion='.$direction)->assertOk()->assertJsonPath('total', 26)->assertJsonPath('last_page', 2)->assertJsonPath('data.0.id', $exact->id);
        $second = $this->getJson('/api/diccionario/buscar?q=abc&direccion='.$direction.'&page=2')->assertOk()->assertJsonCount(6, 'data');

        $this->assertSame(array_merge([$exact->id], $prefixes), array_merge(array_column($first->json('data'), 'id'), array_column($second->json('data'), 'id')));
    }

    #[TestWith(['%', 'kichwa-es'])]
    #[TestWith(['_', 'kichwa-es'])]
    #[TestWith(['\\', 'kichwa-es'])]
    #[TestWith(['%', 'es-kichwa'])]
    #[TestWith(['_', 'es-kichwa'])]
    #[TestWith(['\\', 'es-kichwa'])]
    public function test_search_treats_pattern_characters_as_literal_text_and_ranks_exact_match_first(string $word, string $direction): void
    {
        Diccionario::create(['kichwa' => 'abc', 'español' => 'Sin coincidencia']);
        Diccionario::create(['kichwa' => $word.'abc', 'español' => 'Parcial']);
        $exact = Diccionario::create(['kichwa' => $word, 'español' => 'Exacta']);
        if ($direction === 'es-kichwa') {
            Diccionario::whereKey($exact->id)->update(['español' => $word]);
            Diccionario::where('kichwa', $word.'abc')->update(['español' => $word.'abc']);
        }

        $this->getJson('/api/diccionario/buscar?'.http_build_query(['q' => $word, 'direccion' => $direction]))->assertOk()->assertJsonPath('total', 2)->assertJsonPath('data.0', ['id' => $exact->id, 'kichwa' => $word, 'español' => $direction === 'es-kichwa' ? $word : 'Exacta']);
    }

    public function test_search_is_paginated_at_twenty_and_blank_query_only_suggests_five(): void
    {
        foreach (range(1, 25) as $i) {
            Diccionario::create(['kichwa' => '[DEMO] código '.$i, 'español' => '[DEMO] entrada '.$i]);
        }
        $this->getJson('/api/diccionario/buscar?q=codigo&direccion=kichwa-es')->assertOk()->assertJsonCount(20, 'data')->assertJsonPath('total', 25)->assertJsonPath('last_page', 2);
        $this->getJson('/api/diccionario/buscar?q=codigo&direccion=kichwa-es&page=2')->assertOk()->assertJsonCount(5, 'data');
        $this->getJson('/api/diccionario/buscar?q=&direccion=kichwa-es')->assertOk()->assertJsonCount(5, 'data');
    }

    public function test_csv_import_is_admin_only_atomic_and_preserves_existing_duplicates(): void
    {
        $csv = "kichwa,español\n[DEMO] código,[DEMO] entrada\n";
        Sanctum::actingAs(Usuario::factory()->create());
        $this->postJson('/api/admin/diccionario/import', ['file' => UploadedFile::fake()->createWithContent('entrada.csv', $csv)])->assertForbidden();
        Sanctum::actingAs(Usuario::factory()->administrador()->create());
        $this->postJson('/api/admin/diccionario/import', ['file' => UploadedFile::fake()->createWithContent('entrada.csv', $csv)])->assertCreated()->assertJsonPath('inserted', 1);
        $this->postJson('/api/admin/diccionario/import', ['file' => UploadedFile::fake()->createWithContent('entrada.csv', $csv)])->assertCreated()->assertJsonPath('skipped', 1);
        $this->postJson('/api/admin/diccionario/import', ['file' => UploadedFile::fake()->createWithContent('entrada.csv', "kichwa,español\n[DEMO] otro,entrada\n,inválida\n")])->assertUnprocessable()->assertJsonValidationErrors('file');
        $this->assertDatabaseCount('diccionario', 1);
        $this->assertDatabaseHas('diccionario', ['kichwa' => '[DEMO] código', 'español' => '[DEMO] entrada']);
    }
}
