<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE evaluaciones (
    id_evaluacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad bigint REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    titulo_evaluacion varchar(180) NOT NULL,
    tipo_evaluacion varchar(30) NOT NULL CHECK (tipo_evaluacion IN ('unidad', 'diagnostica')),
    CHECK ((tipo_evaluacion = 'unidad' AND id_unidad IS NOT NULL) OR (tipo_evaluacion = 'diagnostica' AND id_unidad IS NULL))
);
CREATE INDEX ix_evaluaciones_id_unidad ON evaluaciones (id_unidad);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE evaluaciones;
SQL
        );
    }
};
