<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE modulos (
    id_modulo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nivel bigint NOT NULL REFERENCES niveles (id_nivel) ON DELETE RESTRICT,
    nombre_modulo varchar(150) NOT NULL,
    descripcion_modulo text NOT NULL,
    orden_modulo integer NOT NULL CHECK (orden_modulo > 0),
    UNIQUE (id_nivel, orden_modulo)
);
CREATE INDEX ix_modulos_id_nivel ON modulos (id_nivel);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE modulos;
SQL
        );
    }
};
