<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE usuarios_niveles (
    id_usuario_nivel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_nivel bigint NOT NULL REFERENCES niveles (id_nivel) ON DELETE RESTRICT,
    UNIQUE (id_usuario, id_nivel)
);
CREATE INDEX ix_usuarios_niveles_id_usuario ON usuarios_niveles (id_usuario);
CREATE INDEX ix_usuarios_niveles_id_nivel ON usuarios_niveles (id_nivel);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE usuarios_niveles;
SQL
        );
    }
};
