<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE diccionario (
    id_diccionario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palabra_kichwa_diccionario varchar(200) NOT NULL,
    palabra_espanol_diccionario varchar(250) NOT NULL,
    UNIQUE (palabra_kichwa_diccionario, palabra_espanol_diccionario)
);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE diccionario;
SQL
        );
    }
};
