<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE niveles (
    id_nivel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_nivel varchar(80) NOT NULL,
    descripcion_nivel text NOT NULL,
    orden_nivel integer NOT NULL CHECK (orden_nivel > 0),
    UNIQUE (nombre_nivel),
    UNIQUE (orden_nivel)
);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE niveles;
SQL
        );
    }
};
