<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE respuestas_actividad (
    id_respuesta_actividad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL REFERENCES usuarios (id_usuario) ON DELETE RESTRICT,
    id_actividad bigint NOT NULL REFERENCES actividades (id_actividad) ON DELETE RESTRICT,
    respuesta_actividad jsonb NOT NULL CHECK (jsonb_typeof(respuesta_actividad) = 'object'),
    acierto_actividad boolean NOT NULL,
    retroalimentacion_actividad text NOT NULL,
    fecha_respuesta_actividad timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_respuestas_actividad_id_usuario ON respuestas_actividad (id_usuario);
CREATE INDEX ix_respuestas_actividad_id_actividad ON respuestas_actividad (id_actividad);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE respuestas_actividad;
SQL
        );
    }
};
