<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('Esta base requiere PostgreSQL. Configure DB_CONNECTION=pgsql.');
        }
        DB::unprepared(<<<'SQL'
CREATE TABLE temas (
    id_tema bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad bigint NOT NULL REFERENCES unidades (id_unidad) ON DELETE RESTRICT,
    tipo_tema varchar(30) NOT NULL CHECK (tipo_tema IN ('vocabulario', 'gramatica', 'cultura')),
    titulo_tema varchar(180) NOT NULL,
    contenido_tema text NOT NULL,
    orden_tema integer NOT NULL CHECK (orden_tema > 0),
    UNIQUE (id_unidad, orden_tema)
);
CREATE INDEX ix_temas_id_unidad ON temas (id_unidad);

SQL
        );
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
DROP TABLE temas;
SQL
        );
    }
};
